# Generated by Django 4.2.2 on 2023-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('medida', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'verbose_name': 'categoria de productos', 'verbose_name_plural': 'categorias de productos'},
        ),
    ]
